In [1]:
import numpy as np

In [2]:
M = np.array([
        [1,0,0],
        [.5,.5,0],
        [.5,.5,0]])
val, vec = np.linalg.eig(M.T)
val

array([ 1. ,  0.5,  0. ])

In [3]:
M = np.array([
        [.5,0,.5],
        [.5,.5,0],
        [0,.5,.5]])
val, vec = np.linalg.eig(M.T)
val

array([ 0.25+0.4330127j,  0.25-0.4330127j,  1.00+0.j       ])

In [4]:
vec

array([[-0.28867513+0.5j, -0.28867513-0.5j, -0.57735027+0.j ],
       [-0.28867513-0.5j, -0.28867513+0.5j, -0.57735027+0.j ],
       [ 0.57735027+0.j ,  0.57735027-0.j , -0.57735027+0.j ]])

In [5]:
x = np.zeros(3) + 1./3
x

array([ 0.33333333,  0.33333333,  0.33333333])

In [6]:
x.T.dot(M)

array([ 0.33333333,  0.33333333,  0.33333333])

In [7]:
x = np.zeros(3)
x[0] = 1
x

array([ 1.,  0.,  0.])

In [8]:
x.T.dot(M)

array([ 0.5,  0. ,  0.5])

In [9]:
x.T.dot(M).T.dot(M)

array([ 0.25,  0.25,  0.5 ])

In [10]:
x.T.dot(M).T.dot(M).T.dot(M)

array([ 0.25 ,  0.375,  0.375])

In [11]:
def power(x, M, n=10):
    for _ in xrange(n):
        print x
        x = x.T.dot(M)
    return x
        
power(x, M)

[ 1.  0.  0.]
[ 0.5  0.   0.5]
[ 0.25  0.25  0.5 ]
[ 0.25   0.375  0.375]
[ 0.3125  0.375   0.3125]
[ 0.34375  0.34375  0.3125 ]
[ 0.34375   0.328125  0.328125]
[ 0.3359375  0.328125   0.3359375]
[ 0.33203125  0.33203125  0.3359375 ]
[ 0.33203125  0.33398438  0.33398438]


array([ 0.33300781,  0.33398438,  0.33300781])

In [12]:
M = np.array([
        [.5,.25,.25],
        [.25,.5,.25],
        [.25,.25,.5]])
val, vec = np.linalg.eig(M.T)
val

array([ 0.25,  1.  ,  0.25])

In [13]:
vec

array([[-0.81649658,  0.57735027,  0.381008  ],
       [ 0.40824829,  0.57735027, -0.81590361],
       [ 0.40824829,  0.57735027,  0.43489561]])

In [23]:
x

array([ 1.,  0.,  0.])

In [15]:
power(x, M)

[ 1.  0.  0.]
[ 0.5   0.25  0.25]
[ 0.375   0.3125  0.3125]
[ 0.34375   0.328125  0.328125]
[ 0.3359375   0.33203125  0.33203125]
[ 0.33398438  0.33300781  0.33300781]
[ 0.33349609  0.33325195  0.33325195]
[ 0.33337402  0.33331299  0.33331299]
[ 0.33334351  0.33332825  0.33332825]
[ 0.33333588  0.33333206  0.33333206]


array([ 0.33333397,  0.33333302,  0.33333302])

In [16]:
M = np.array([
        [.75,.25,0],
        [0,.5,.5],
        [.75,0,.25]])
val, vec = np.linalg.eig(M.T)
val

array([ 1.00+0.j        ,  0.25+0.35355339j,  0.25-0.35355339j])

In [17]:
vec

array([[-0.85714286+0.j        ,  0.70710678+0.j        ,  0.70710678-0.j        ],
       [-0.42857143+0.j        , -0.23570226-0.33333333j,
        -0.23570226+0.33333333j],
       [-0.28571429+0.j        , -0.47140452+0.33333333j,
        -0.47140452-0.33333333j]])

In [18]:
v = power(x, M)

[ 1.  0.  0.]
[ 0.75  0.25  0.  ]
[ 0.5625  0.3125  0.125 ]
[ 0.515625  0.296875  0.1875  ]
[ 0.52734375  0.27734375  0.1953125 ]
[ 0.54199219  0.27050781  0.1875    ]
[ 0.54711914  0.27075195  0.18212891]
[ 0.54693604  0.27215576  0.1809082 ]
[ 0.54588318  0.27281189  0.18130493]
[ 0.54539108  0.27287674  0.18173218]


In [22]:
sum(v**2)

0.40488787244066771

In [19]:
v * 2

array([ 1.09068489,  0.54557228,  0.36374283])

In [44]:
v = vec[:,0]
v

array([-0.85714286+0.j, -0.42857143+0.j, -0.28571429+0.j])

In [45]:
v / v.sum()

array([ 0.54545455-0.j,  0.27272727-0.j,  0.18181818-0.j])

In [62]:
M = np.array([
        [1,0,0],
        [1,0,0],
        [.5,.5,0]])
val, vec = np.linalg.eig(M.T)
val

array([ 1.,  0.,  0.])

In [63]:
vec

array([[  1.00000000e+000,  -7.07106781e-001,   7.07106781e-001],
       [  0.00000000e+000,   7.07106781e-001,  -7.07106781e-001],
       [  0.00000000e+000,   0.00000000e+000,   4.25148311e-292]])

In [64]:
M = np.array([
        [1,0,0],
        [.5,.5,0],
        [.5,.5,0]])
val, vec = np.linalg.eig(M.T)
val

array([ 1. ,  0.5,  0. ])

In [65]:
vec

array([[ 1.        , -0.70710678,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678],
       [ 0.        ,  0.        ,  0.70710678]])